const PropertyDetail = [
  {
    id: "1",
    Image: "../../Images/Logement/logement2.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "1 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bathRoom",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "2",
    Image: "../../Images/Logement/logement1.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "2 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "3",
    Image: "../../Images/Logement/logement3.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "2 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "4",
    Image: "../../Images/Logement/logement4.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "2 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "5",
    Image: "../../Images/Logement/logement5.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "2 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "6",
    Image: "../../Images/Logement/logement6.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "1 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "7",
    Image: "../../Images/Logement/logement7.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "2 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "8",
    Image: "../../Images/Logement/logement8.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "1 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
  {
    id: "9",
    Image: "../../Images/Logement/logement5.jpg",
    heading: "Le Barycentre",
    span: "Voir plus",
    ville: "Caen",
    surface: "21m²",
    size: "45m²",
    amount:"367€",
    bed: "1 bed",
    bedImage: "../../Images/Logement/bed.png",
    bath: "Preview bath",
    bathImage: "../../Images/Logement/bath.png",
  },
];

export default PropertyDetail;
